### ISSUE TITLE
update coteditor version from 2.7.0 to latest version

### ISSUE THREAD

**Issue by ghost** [coteditor/homebrew-coteditor#3]
The homebrew formula references coteditor version 2.7.0 and could be updated to reference the latest version. At the time of writing this issue the latest version was 3.7.5.

**Comment by 1024jp** [comment]
Do you talk about `cot` command or CotEditor.app?
This repository is for `cot` command, of which the latest version is 2.7.4.

Regarding CotEditor.app, the CotEditor project does not support homebrew cask officially.
Somebody maintains it voluntarily, but it's not our task.

**Comment by ghost** [comment]
@1024jp I have only recently discovered the cot project so wasn't aware of the versioning differences between the app and cli tool. Thanks for letting me know more about this.
